---
title: "Figures_Results"
author: "John Schoof"
date: "5/30/2020"
output: html_document
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
  if (Sys.getenv("USER") == "david") {
    knitr::opts_knit$set(root.dir = "/Users/david/Desktop/Dave/school/Epi 514/Final Project/Analysis/")
  }
  
  #Matt's system
  if (Sys.getenv("USER") == "msgoldberg") {
    knitr::opts_knit$set(root.dir = "/Users/msgoldberg/Desktop/Grad_School/Year_1/Q3/EPI514/SSB_Paper/")
  }

  if (Sys.getenv("USER") == "jscho") {
    knitr::opts_knit$set(root.dir = "C:/Users/jscho/OneDrive - UW/SPRING 2020-LAPTOP-7K6NFTGB/EPI 514/")
  }


```




```{r load_packages}

library(tidyverse) #suite of packages for data cleaning and manipulation
library(epiR) #basic epi tools including stratified analysis with Mantel Haenszel
library(survey) #survey package to calculate survey sample weighted prevalence
if (!require(sjPlot)) install.packages("sjPlot")
library(sjPlot)
if (!require(stargazer)) install.packages("stargazer")
library(stargazer)
if (!require(kableExtra)) install.packages("kableExtra")
library(kableExtra)
if (!require(htmlTable)) install.packages("htmlTable")
library(htmlTable)
library(dplyr)
library(ggplot2)
```




```{r create_data}

# Create vectors of results
  id <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)  
  #prev <- c("29.4%", "34.2", "41.0%")
  rr <- c(1.13, 1.33, 0.98, 1.19, 1.14, 1.31, 1.12, 1.31, 1.11, 1.30)
  upper <- c(1.17, 1.37, 1.11, 1.32, 1.21, 1.38, 1.20, 1.39, 1.19, 1.40)
  lower <- c(1.09, 1.29, 0.87, 1.07, 1.07, 1.24, 1.05, 1.24, 1.03, 1.21)
  adjusted <- c("Adjusted", "Adjusted", "No HS", "No HS", "HS Graduate", "HS Graduate", "Some College", "Some College", "College Graduate", "College Graduate")
  consumption <- c(1, 2, 1, 2, 1, 2, 1, 2, 1, 2)
  #rr_string <- c("Ref", "1.13 (1.09, 1.17)", "1.33 (1.29, 1.37)")
  
  

# Create dataframe of results
  df <- data.frame(id, rr, upper, lower, adjusted, consumption)
  
  #df$id <- factor(df$id, levels = df$id)
  
  df$adjusted <- factor(df$adjusted, 
                    levels = c("Adjusted", "No HS", "HS Graduate", "Some College", "College Graduate"))
  
  df$consumption <- factor(df$consumption, 
                    levels = c(1, 2), 
                    labels = c("1-2 SSB", ">2 SSB"))



```



```{r}


## base plot
 ggplot(data = df, aes(x = consumption, y = rr)) +
   
   ## change the theme
   # apply basic black and white theme - this theme removes the background colour by default
     theme_bw() + 
     # remove gridlines. panel.grid.major is for verical lines, panel.grid.minor is for horizontal lines
     theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
       # remove borders
       panel.border = element_blank(),
       # removing borders also removes x and y axes. Add them back
       axis.line = element_line()) + 
   
   ## add bars
   geom_bar(stat = "identity", aes(fill = adjusted), position = "dodge") + 
     #scale_fill_manual(values = c("#999999", "#CCCCCC")) + 
   
   ## make the plot horizontal
   coord_flip() + 
   
   ## add facets 
   facet_grid(rows = vars(adjusted), scales = "free_y", space = "free_y", switch = "y") + 
    # move facet label outside the chart area i.e. continent names should be to the left of country names
   theme(strip.placement = "outside",
         # remove background colour from facet labels
         strip.background  = element_blank(),
         # remove border from facet label
        panel.border = element_blank(), 
        # make continent names horizontal
        strip.text.y = element_text(angle = 180)) + 
 
   ## remove legend
   guides(fill = FALSE) + 
  
   ## adjust range of RRs
   ylim(0, 1.75) +
   
   ## Add error bars
   geom_errorbar(aes(ymin=lower, ymax=upper),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9)) +
  
   ## modify graph labels
   # remove x-axis label
   xlab("") +
   # change the y-axis label
   ylab("Relative Risk") + 
   # add caption and title
   labs(title = "Figure 2. Relative risks of decreased sleep duration by SSB consumption", 
caption = "Data source: BRFSS 2016")


ggsave("figure2_results.png")

```





```{r forest_plot}


forest <- ggplot(df, aes(x=consumption, y=rr, ymin=lower, ymax=upper)) +
              

              geom_point(stat = "identity", aes(fill = adjusted), position = "dodge") + 
              geom_errorbar(aes(min=lower, max=upper, width = .3)) +
              geom_hline(yintercept=1, lty=2) +  # add a dotted line at x=1 after flip
              coord_flip() +  # flip coordinates (puts labels on y axis)
  
              ## add facets
              facet_grid(rows = vars(adjusted), scales = "free_y", space = "free_y", switch = "y") + 
              # move facet label outside the chart area i.e. continent names should be to the left of country names
              theme(strip.placement = "outside",
              # remove background colour from facet labels
              strip.background  = element_blank(),
              # remove border from facet label
              panel.border = element_blank(), 
              # make continent names horizontal
              strip.text.y = element_text(angle = 180)) + 
 
              ## remove legend
              guides(fill = FALSE) + 
              
              labs(x= "Average Daily SSB Consumtion (in beverages)",
                         y= "Relative Risk of Shortened Sleep",
                         title= "Figure 1. Relative Risks") +
              ylim(0.75, 1.5) +
              theme_classic()  # use a white background

print(forest)


```



```{r}

fp <- df %>%
  as_tibble() %>%
  ggplot(aes(y=consumption, x=rr, label=consumption)) +
    geom_point(size=2, shape=19) +
    geom_errorbarh(aes(xmin=lower, xmax=upper), height=.3) +
    geom_vline(xintercept=1, linetype='longdash') +
    facet_wrap(~adjusted, ncol=1) +
    # remove background colour from facet labels
    theme(strip.background = element_blank(),
          
          axis.title.y = element_text(margin = margin(r = 10)),
          axis.title.x = element_text(margin = margin(r = 10)),
          # remove border from facet label
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank())+
          #axis.line = element_line(colour = "grey50")) + 
    labs(y= "Average Daily SSB Consumtion (in beverages)",
                         x= "Relative Risk of Shortened Sleep",
                         title= "Figure 1. Relative Risks") 
    #theme_classic()  # use a white background

print(fp)


```



