---
title: "SSB_SensitivityAnalysis_SodavsOther"
author: "John Schoof"
date: "5/29/2020"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
  if (Sys.getenv("USER") == "david") {
    knitr::opts_knit$set(root.dir = "/Users/david/Desktop/Dave/school/Epi 514/Final Project/Analysis/")
  }
  
  #Matt's system
  if (Sys.getenv("USER") == "msgoldberg") {
    knitr::opts_knit$set(root.dir = "/Users/msgoldberg/Desktop/Grad_School/Year_1/Q3/EPI514/SSB_Paper/")
  }

  if (Sys.getenv("USER") == "jscho") {
    knitr::opts_knit$set(root.dir = "C:/Users/jscho/OneDrive - UW/SPRING 2020-LAPTOP-7K6NFTGB/EPI 514/")
  }


```



```{r load_packages}

library(tidyverse) #suite of packages for data cleaning and manipulation
library(epiR) #basic epi tools including stratified analysis with Mantel Haenszel
library(survey) #survey package to calculate survey sample weighted prevalence
if (!require(sjPlot)) install.packages("sjPlot")
library(sjPlot)
if (!require(stargazer)) install.packages("stargazer")
library(stargazer)
if (!require(kableExtra)) install.packages("kableExtra")
library(kableExtra)
if (!require(htmlTable)) install.packages("htmlTable")
library(htmlTable)
library(dplyr)
```



```{r load_data}

# If you want the CSV choose this option
#data <- read_csv("Data/SSB_master.csv")

# For R data file
  load("Data/SSB_master.RData")
  data <- SSB_master

```




```{r survey_weights}

#DMC - why is there no cluster design in the weights?
#creating survey weight object
  design <- svydesign(ids = ~1, 
                      weights= ~final_weight,
                      strata = ~ststr, 
                      data=data)
  options(survey.lonely.psu = "adjust") #setting for how to deal with a psu with a single observation
  

```





```{r}

# create categorical soda variable 1
 data$soda_cat1 <- data$soda
      data <- data %>% mutate(soda_cat1 = case_when(soda<1 ~ 0,
                                                    soda>=1 & soda<2 ~ 1,
                                                    soda>=2 ~ 2))
    
      data$soda_cat1 <- factor(data$soda_cat1,
                           levels = c(0, 1, 2),
                           labels = c("<1 sodas per Day", "[1-2) sodas per Day", 
                                      "2+ sodas per Day"))
      

# create categorical juice variable 1
 data$juice_cat1 <- data$juice
      data <- data %>% mutate(juice_cat1 = case_when(juice<1 ~ 0,
                                                    juice>=1 & juice<2 ~ 1,
                                                    juice>=2 ~ 2))
    
      data$juice_cat1 <- factor(data$juice_cat1,
                           levels = c(0, 1, 2),
                           labels = c("<1 juices per Day", "[1-2) juices per Day", 
                                      "2+ juices per Day"))

```




```{r prepare_2X2}

# Relevel outcome as 1/2 format
  data$sleep_01 <- fct_relevel(data$sleep_01,
                         "<7 Hours of Sleep", "7+ Hours of Sleep")

# Split exposure variable into 2 binary variables for soda and juice

# SODA
  # Create binary exposure variable - [1-2) vs <1 (reference category)
  data$soda_cat1_low <- as.numeric(data$soda_cat1)
  table(data$ssb_cat1_low)
  
  data$soda_cat1_low[data$soda_cat1_low==3] <- NA
  
  data$soda_cat1_low <- factor(data$soda_cat1_low,
                                levels=c(2,1),
                                labels=c("[1-2) Sodas per Day", "<1 Sodas per Day"))
  
  # Create binary exposure variable - 2+ vs <1 (reference category)
  data$soda_cat1_high <- as.numeric(data$soda_cat1)
  table(data$soda_cat1_high)
  
  data$soda_cat1_high[data$soda_cat1_high==2] <- NA
  
  data$soda_cat1_high <- factor(data$soda_cat1_high,
                                  levels=c(3,1),
                                  labels=c("2+ Sodas per Day", "<1 Sodas per Day"))

  
# OTHER SSBs
  # Create binary exposure variable - [1-2) vs <1 (reference category)
  data$juice_cat1_low <- as.numeric(data$juice_cat1)
  table(data$juice_cat1_low)
  
  data$juice_cat1_low[data$juice_cat1_low==3] <- NA
  
  data$juice_cat1_low <- factor(data$juice_cat1_low,
                                levels=c(2,1),
                                labels=c("[1-2) Other SSBs per Day", "<1 Other SSBs per Day"))
  
  # Create binary exposure variable - 2+ vs <1 (reference category)
  data$juice_cat1_high <- as.numeric(data$juice_cat1)
  table(data$juice_cat1_high)
  
  data$juice_cat1_high[data$juice_cat1_high==2] <- NA
  
  data$juice_cat1_high <- factor(data$juice_cat1_high,
                                  levels=c(3,1),
                                  labels=c("2+ Other SSBs per Day", "<1 Other SSBs per Day"))
  
  
  #Check newly coded variables
    # Soda
    with(data, table(soda_cat1_low, soda_cat1))
    with(data, table(soda_cat1_high, soda_cat1))
    
    # Other SSBs
    with(data, table(juice_cat1_low, juice_cat1))
    with(data, table(juice_cat1_high, juice_cat1))
    
  #SSB tables coded correctly
    
    

  #Checking sleep X ssb tables
    # Soda
    (base_table_soda_low <- with(data, table(soda_cat1_low, sleep_01)))
    (base_table_soda_high <- with(data, table(soda_cat1_high, sleep_01)))
    
    # Juice
    (base_table_juice_low <- with(data, table(juice_cat1_low, sleep_01)))
    (base_table_juice_high <- with(data, table(juice_cat1_high, sleep_01)))
    
  #Tables set up correctly


  # Change factor covariates into numeric
    data$age_cat <- as.numeric(data$age_cat)
    data$sex_01 <- as.numeric(data$sex_01)
    data$education <- as.numeric(data$education)
    data$exercise_01 <- as.numeric(data$exercise_01)
    data$mental <- as.numeric(data$mental)
    data$diabetes_01 <- as.numeric(data$diabetes_01)
    data$smoking_01 <- as.numeric(data$smoking_01)
    data$bmi_cat <- as.numeric(data$bmi_cat)


  # Setting up covariates into tables
    # Soda
    adj_table_soda_low <- with(data, table(soda_cat1_low, sleep_01,
                          age_cat+sex_01+education+exercise_01+mental+diabetes_01+smoking_01+bmi_cat))
    
    adj_table_soda_high <- with(data, table(soda_cat1_high, sleep_01, 
                          age_cat+sex_01+education+exercise_01+mental+diabetes_01+smoking_01+bmi_cat))
    
    adj_table_soda_low <- with(data, table(soda_cat1_low, sleep_01, 
                          age_cat+sex_01+exercise_01+diabetes_01+smoking_01+bmi_cat))
    
    # Other SSB
    adj_table_juice_low <- with(data, table(juice_cat1_low, sleep_01,
                          age_cat+sex_01+education+exercise_01+mental+diabetes_01+smoking_01+bmi_cat))
    
    adj_table_juice_high <- with(data, table(juice_cat1_high, sleep_01, 
                          age_cat+sex_01+education+exercise_01+mental+diabetes_01+smoking_01+bmi_cat))
    
    adj_table_juice_low <- with(data, table(juice_cat1_low, sleep_01, 
                          age_cat+sex_01+exercise_01+diabetes_01+smoking_01+bmi_cat))
    
  #adding mental and BMI changes the crude PR - why is this?


```





```{r M-H_analysis}
# SODA
  #unadjusted low PR
    (low_base_soda <- epi.2by2(base_table_soda_low, method="cross.sectional"))
  
  #unadjusted high PR
    (high_base_soda <- epi.2by2(base_table_soda_high, method="cross.sectional"))
  
  #adjusted low PR
    (low_adj_soda <- epi.2by2(adj_table_soda_low, method="cross.sectional"))
    ## ERROR
  
  #adjusted high PR
    (high_adj_soda <- epi.2by2(adj_table_soda_high, method="cross.sectional"))


# OTHER SSBs
  #unadjusted low PR
    (low_base_juice <- epi.2by2(base_table_juice_low, method="cross.sectional"))
  
  #unadjusted high PR
    (high_base_juice <- epi.2by2(base_table_juice_high, method="cross.sectional"))
  
  #adjusted low PR
    (low_adj_juice <- epi.2by2(adj_table_juice_low, method="cross.sectional"))
  
  #adjusted high PR
    (high_adj_juice <- epi.2by2(adj_table_juice_high, method="cross.sectional"))

```








