---
title: "Table 1 Soda vs Other SSB"
author: "John Schoof"
date: "5/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
  if (Sys.getenv("USER") == "david") {
    knitr::opts_knit$set(root.dir = "/Users/david/Desktop/Dave/school/Epi 514/Final Project/Analysis/")
  }
  
  #Matt's system
  if (Sys.getenv("USER") == "msgoldberg") {
    knitr::opts_knit$set(root.dir = "/Users/msgoldberg/Desktop/Grad_School/Year_1/Q3/EPI514/SSB_Paper/")
  }

  if (Sys.getenv("USER") == "jscho") {
    knitr::opts_knit$set(root.dir = "C:/Users/jscho/OneDrive - UW/SPRING 2020-LAPTOP-7K6NFTGB/EPI 514/")
  }


```




```{r load_packages}

library(tidyverse) #suite of packages for data cleaning and manipulation
library(epiR) #basic epi tools including stratified analysis with Mantel Haenszel
library(survey) #survey package to calculate survey sample weighted prevalence
if (!require(sjPlot)) install.packages("sjPlot")
library(sjPlot)
if (!require(stargazer)) install.packages("stargazer")
library(stargazer)
if (!require(kableExtra)) install.packages("kableExtra")
library(kableExtra)
if (!require(htmlTable)) install.packages("htmlTable")
library(htmlTable)
library(dplyr)

```





```{r load_data}

# Load Data
#SSB_master <- readRDS("Data/SSB_master.Rds")
load("Data/SSB_master.RData")
glimpse(SSB_master)

```





```{r survey_weights}

library("survey")
  SSB_master <- subset(SSB_master, !is.na(final_weight))
  design <- svydesign(data = SSB_master, 
                      id = ~1, 
                      strata  = ~ststr, 
                      weights = ~final_weight, 
                      nest = TRUE)
  
  #setting for how to deal with a psu with a single observation
  options(survey.lonely.psu = "adjust") 

```



```{r}

# create categorical soda variable 1
 SSB_master$soda_cat1 <- SSB_master$soda
      SSB_master <- SSB_master %>% mutate(soda_cat1 = case_when(soda<1 ~ 0,
                                                    soda>=1 & soda<2 ~ 1,
                                                    soda>=2 ~ 2))
    
      SSB_master$soda_cat1 <- factor(SSB_master$soda_cat1,
                           levels = c(0, 1, 2),
                           labels = c("<1 sodas per Day", "[1-2) sodas per Day", 
                                      "2+ sodas per Day"))
      

# create categorical juice variable 1
 SSB_master$juice_cat1 <- SSB_master$juice
      SSB_master <- SSB_master %>% mutate(juice_cat1 = case_when(juice<1 ~ 0,
                                                    juice>=1 & juice<2 ~ 1,
                                                    juice>=2 ~ 2))
    
      SSB_master$juice_cat1 <- factor(SSB_master$juice_cat1,
                           levels = c(0, 1, 2),
                           labels = c("<1 juices per Day", "[1-2) juices per Day", 
                                      "2+ juices per Day"))
      
      
    

```







```{r}

#N table soda cat 1
(n_table_soda1 <- table(SSB_master$soda_cat1, useNA = "always"))

# weighted proportion table
n_svy_soda1 <- svytable(~SSB_master$soda_cat1, design = design)
n_prop_soda1 <- prop.table(n_svy_soda1)


#N table juice cat 1
(n_table_juice1 <- table(SSB_master$juice_cat1, useNA = "always"))

# weighted proportion table
n_svy_juice1 <- svytable(~SSB_master$juice_cat1, design = design)
n_prop_juice1 <- prop.table(n_svy_juice1)




```





```{r freq_tables cat1}


# AGE
  
  # Soda
  # frequency table
  age_table_soda1 <- table(SSB_master$age_cat, 
                      SSB_master$soda_cat1, 
                      deparse.level = 2) # No NAs
  
  # weighted proportion table
  age_svy_soda1 <- svytable(~age_cat + SSB_master$soda_cat1, design = design)
  age_prop_soda1 <- prop.table(age_svy_soda1, 2)
  
  # Juice
  # frequency table
  age_table_juice1 <- table(SSB_master$age_cat, 
                      SSB_master$juice_cat1, 
                      deparse.level = 2) # No NAs
  
  # weighted proportion table
  age_svy_juice1 <- svytable(~age_cat + SSB_master$juice_cat1, design = design)
  age_prop_juice1 <- prop.table(age_svy_juice1, 2)
  

# SEX
  
  # Soda
  # frequency table
  sex_table_soda1 <- table(SSB_master$sex_01, 
                      SSB_master$soda_cat1, 
                      deparse.level = 2) # No NAs
  
  # weighted proportion table
  sex_svy_soda1 <- svytable(~sex_01 + SSB_master$soda_cat1, design = design)
  sex_prop_soda1 <- prop.table(sex_svy_soda1, 2)
  
  # Juice
  # frequency table
  sex_table_juice1 <- table(SSB_master$sex_01, 
                      SSB_master$juice_cat1, 
                      deparse.level = 2) # No NAs
  
  # weighted proportion table
  sex_svy_juice1 <- svytable(~sex_01 + SSB_master$juice_cat1, design = design)
  sex_prop_juice1 <- prop.table(sex_svy_juice1, 2)
  

# EDUCATION
  
  # Soda
  # frequency table
  education_table_soda1 <- table(SSB_master$education, 
                            SSB_master$soda_cat1, 
                            deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  education_svy_soda1 <- svytable(~education + SSB_master$soda_cat1, design = design)
  education_prop_soda1 <- prop.table(education_svy_soda1, 2)

  # Juice
  # frequency table
  education_table_juice1 <- table(SSB_master$education, 
                            SSB_master$juice_cat1, 
                            deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  education_svy_juice1 <- svytable(~education + SSB_master$juice_cat1, design = design)
  education_prop_juice1 <- prop.table(education_svy_juice1, 2)
  
  
# INCOME
  
  # frequency table
  #(income_table <- table(SSB_master$income_cat, 
  #                       SSB_master$ssb_cat, 
  #                       deparse.level = 2, useNA = "always"))
  #
  # weighted proportion table
  #income_svy <- svytable(~income_cat + ssb_cat, design = design)
  #prop.table(income_svy, 2)
  

# EXERCISE
  
  # Soda
  # frequency table
  exercise_table_soda1 <- table(SSB_master$exercise_01, 
                           SSB_master$soda_cat1, 
                           deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  exercise_svy_soda1 <- svytable(~exercise_01 + SSB_master$soda_cat1, design = design)
  exercise_prop_soda1 <- prop.table(exercise_svy_soda1, 2)
  
  # Juice
  # frequency table
  exercise_table_juice1 <- table(SSB_master$exercise_01, 
                           SSB_master$juice_cat1, 
                           deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  exercise_svy_juice1 <- svytable(~exercise_01 + SSB_master$juice_cat1, design = design)
  exercise_prop_juice1 <- prop.table(exercise_svy_juice1, 2)
  

# MENTAL HEALTH
  
  # Soda
  # frequency table
  mental_table_soda1 <- table(SSB_master$mental, 
                         SSB_master$soda_cat1, 
                         deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  mental_svy_soda1 <- svytable(~mental + SSB_master$soda_cat1, design = design)
  mental_prop_soda1 <- prop.table(mental_svy_soda1, 2)

  # Juice
  # frequency table
  mental_table_juice1 <- table(SSB_master$mental, 
                         SSB_master$juice_cat1, 
                         deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  mental_svy_juice1 <- svytable(~mental + SSB_master$juice_cat1, design = design)
  mental_prop_juice1 <- prop.table(mental_svy_juice1, 2)
  
  
# DIABETES
  
  # Soda
  # frequency table
  diabetes_table_soda1 <- table(SSB_master$diabetes_01, 
                           SSB_master$soda_cat1, 
                           deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  diabetes_svy_soda1 <- svytable(~diabetes_01 + SSB_master$soda_cat1, design = design)
  diabetes_prop_soda1 <- prop.table(diabetes_svy_soda1, 2)
  
  # Juice
  # frequency table
  diabetes_table_juice1 <- table(SSB_master$diabetes_01, 
                           SSB_master$juice_cat1, 
                           deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  diabetes_svy_juice1 <- svytable(~diabetes_01 + SSB_master$juice_cat1, design = design)
  diabetes_prop_juice1 <- prop.table(diabetes_svy_juice1, 2)

  
  

# SMOKING
  
  # Soda
  # frequency table
  smoking_table_soda1 <- table(SSB_master$smoking_01, 
                          SSB_master$soda_cat1, 
                          deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  smoking_svy_soda1 <- svytable(~smoking_01 + SSB_master$soda_cat1, design = design)
  smoking_prop_soda1 <- prop.table(smoking_svy_soda1, 2)
  
  # Juice
  # frequency table
  smoking_table_juice1 <- table(SSB_master$smoking_01, 
                          SSB_master$juice_cat1, 
                          deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  smoking_svy_juice1 <- svytable(~smoking_01 + SSB_master$juice_cat1, design = design)
  smoking_prop_juice1 <- prop.table(smoking_svy_juice1, 2)
  

# BMI
  
  # Soda
  # frequency table
  bmi_table_soda1 <- table(SSB_master$bmi_cat, 
                      SSB_master$soda_cat1, 
                      deparse.level = 2, useNA = "always") 
                      # <1 category missing more than 5%
  
  # weighted proportion table
  bmi_svy_soda1 <- svytable(~bmi_cat + SSB_master$soda_cat1, design = design)
  bmi_prop_soda1 <- prop.table(bmi_svy_soda1, 2)
  
  
  # frequency table
  bmi_table_juice1 <- table(SSB_master$bmi_cat, 
                      SSB_master$juice_cat1, 
                      deparse.level = 2, useNA = "always") 
                      # <1 category missing more than 5%
  
  # weighted proportion table
  bmi_svy_juice1 <- svytable(~bmi_cat + SSB_master$juice_cat1, design = design)
  bmi_prop_juice1 <- prop.table(bmi_svy_juice1, 2)
  
  

# ALCOHOL
  
  # frequency table
  # (alcohol_table <- table(SSB_master$alcohol_cat, 
  #                        SSB_master$ssb_cat, 
  #                        deparse.level = 2, useNA = "always"))
  
  # weighted proportion table
  #alcohol_svy <- svytable(~alcohol_cat + ssb_cat, design = design)
  #prop.table(alcohol_svy, 2)



```






```{r table cat1}

tables_cat1 <- rbind(age_prop_soda1, age_prop_juice1, sex_prop_soda1, sex_prop_juice1, education_prop_soda1, education_prop_juice1, exercise_prop_soda1, exercise_prop_juice1, mental_prop_soda1, mental_prop_juice1, diabetes_prop_soda1, diabetes_prop_juice1, smoking_prop_soda1, smoking_prop_juice1, bmi_prop_soda1, bmi_prop_juice1)

#changing into percentage
tables_cat1 <- round(tables_cat1, 2)
tables_cat1 <- tables_cat1*100
tables_cat1[,1:3] <- paste(tables_cat1[,1:3], "%", sep="") 

glimpse(subset(SSB_master, soda_cat1=="<1 sodas per Day"))  # 48,569 observations
glimpse(subset(SSB_master, soda_cat1=="[1-2) sodas per Day"))  # 5,322 observations
glimpse(subset(SSB_master, soda_cat1=="2+ sodas per Day"))  # 3,700 observations



# name <- data.frame(Model = c("Age", "18-24", "25-34", "35-44", "45-54", "55-64", "65+", "Sex", "Male", "Female", "Education", "Did not graduate HS", "HS graduate", "Some college", "College graduate", "Exercise", "Exercised in the past 30 days", "No exercise in the past 30 days", "Poor Mental Health Days", "Less than 14", "14 or more", "Diabetes", "No", "Yes", "Current Smoking Status", "Non-smoker", "Smoker", "BMI", "Less than 25", "25-29.9", "30 or higher"))


table1_sodavsother_cat1 <- stargazer(tables_cat1, summary=FALSE, rownames=TRUE, type="html", 
              title = "Table 1. Descriptive statistics of sample by average daily soda vs other SSB.(n = 85,760)",
              align=TRUE,
              style="ajs",
              out="Table1_SodavsOther_cat1.doc")


```




```{r create cat2 variables}


# create categorical soda variable 2
 SSB_master$soda_cat2 <- SSB_master$soda
      SSB_master <- SSB_master %>% mutate(soda_cat2 = case_when(soda==0 ~ 0,
                                                    soda>0 & soda<1 ~ 1,
                                                    soda>=1 ~ 2))
    
      SSB_master$soda_cat2 <- factor(SSB_master$soda_cat2,
                           levels = c(0, 1, 2),
                           labels = c("0 sodas per Day", "(0-1) sodas per Day", 
                                      "1+ sodas per Day"))


# create categorical juice variable 2
 SSB_master$juice_cat2 <- SSB_master$juice
      SSB_master <- SSB_master %>% mutate(juice_cat2 = case_when(juice==0 ~ 0,
                                                    juice>0 & juice<1 ~ 1,
                                                    juice>=1 ~ 2))
    
      SSB_master$juice_cat2 <- factor(SSB_master$juice_cat2,
                           levels = c(0, 1, 2),
                           labels = c("0 juices per Day", "(0-1) juices per Day", 
                                      "1+ juices per Day"))     
      


```





```{r N table cat2}



#N table soda cat 2
(n_table_soda2 <- table(SSB_master$soda_cat2, useNA = "always"))

# weighted proportion table
n_svy_soda2 <- svytable(~SSB_master$soda_cat2, design = design)
n_prop_soda2 <- prop.table(n_svy_soda2)


#N table juice cat 2
(n_table_juice2 <- table(SSB_master$juice_cat2, useNA = "always"))

# weighted proportion table
n_svy_juice2 <- svytable(~SSB_master$juice_cat2, design = design)
n_prop_juice2 <- prop.table(n_svy_juice2)


```





```{r frerquency tables cat2}


# AGE
  
  # Soda
  # frequency table
  age_table_soda2 <- table(SSB_master$age_cat, 
                      SSB_master$soda_cat2, 
                      deparse.level = 2) # No NAs
  
  # weighted proportion table
  age_svy_soda2 <- svytable(~age_cat + SSB_master$soda_cat2, design = design)
  age_prop_soda2 <- prop.table(age_svy_soda2, 2)
  
  # Juice
  # frequency table
  age_table_juice2 <- table(SSB_master$age_cat, 
                      SSB_master$juice_cat2, 
                      deparse.level = 2) # No NAs
  
  # weighted proportion table
  age_svy_juice2 <- svytable(~age_cat + SSB_master$juice_cat2, design = design)
  age_prop_juice2 <- prop.table(age_svy_juice2, 2)
  

# SEX
  
  # Soda
  # frequency table
  sex_table_soda2 <- table(SSB_master$sex_01, 
                      SSB_master$soda_cat2, 
                      deparse.level = 2) # No NAs
  
  # weighted proportion table
  sex_svy_soda2 <- svytable(~sex_01 + SSB_master$soda_cat2, design = design)
  sex_prop_soda2 <- prop.table(sex_svy_soda2, 2)
  
  # Juice
  # frequency table
  sex_table_juice2 <- table(SSB_master$sex_01, 
                      SSB_master$juice_cat2, 
                      deparse.level = 2) # No NAs
  
  # weighted proportion table
  sex_svy_juice2 <- svytable(~sex_01 + SSB_master$juice_cat2, design = design)
  sex_prop_juice2 <- prop.table(sex_svy_juice2, 2)
  

# EDUCATION
  
  # Soda
  # frequency table
  education_table_soda2 <- table(SSB_master$education, 
                            SSB_master$soda_cat1, 
                            deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  education_svy_soda2 <- svytable(~education + SSB_master$soda_cat2, design = design)
  education_prop_soda2 <- prop.table(education_svy_soda2, 2)

  # Juice
  # frequency table
  education_table_juice2 <- table(SSB_master$education, 
                            SSB_master$juice_cat2, 
                            deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  education_svy_juice2 <- svytable(~education + SSB_master$juice_cat2, design = design)
  education_prop_juice2 <- prop.table(education_svy_juice2, 2)
  
  
# INCOME
  
  # frequency table
  #(income_table <- table(SSB_master$income_cat, 
  #                       SSB_master$ssb_cat, 
  #                       deparse.level = 2, useNA = "always"))
  #
  # weighted proportion table
  #income_svy <- svytable(~income_cat + ssb_cat, design = design)
  #prop.table(income_svy, 2)
  

# EXERCISE
  
  # Soda
  # frequency table
  exercise_table_soda2 <- table(SSB_master$exercise_01, 
                           SSB_master$soda_cat2, 
                           deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  exercise_svy_soda2 <- svytable(~exercise_01 + SSB_master$soda_cat2, design = design)
  exercise_prop_soda2 <- prop.table(exercise_svy_soda2, 2)
  
  # Juice
  # frequency table
  exercise_table_juice2 <- table(SSB_master$exercise_01, 
                           SSB_master$juice_cat2, 
                           deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  exercise_svy_juice2 <- svytable(~exercise_01 + SSB_master$juice_cat2, design = design)
  exercise_prop_juice2 <- prop.table(exercise_svy_juice2, 2)
  

# MENTAL HEALTH
  
  # Soda
  # frequency table
  mental_table_soda2 <- table(SSB_master$mental, 
                         SSB_master$soda_cat2, 
                         deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  mental_svy_soda2 <- svytable(~mental + SSB_master$soda_cat2, design = design)
  mental_prop_soda2 <- prop.table(mental_svy_soda2, 2)

  # Juice
  # frequency table
  mental_table_juice2 <- table(SSB_master$mental, 
                         SSB_master$juice_cat2, 
                         deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  mental_svy_juice2 <- svytable(~mental + SSB_master$juice_cat2, design = design)
  mental_prop_juice2 <- prop.table(mental_svy_juice2, 2)
  
  
# DIABETES
  
  # Soda
  # frequency table
  diabetes_table_soda2 <- table(SSB_master$diabetes_01, 
                           SSB_master$soda_cat2, 
                           deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  diabetes_svy_soda2 <- svytable(~diabetes_01 + SSB_master$soda_cat2, design = design)
  diabetes_prop_soda2 <- prop.table(diabetes_svy_soda2, 2)
  
  # Juice
  # frequency table
  diabetes_table_juice2 <- table(SSB_master$diabetes_01, 
                           SSB_master$juice_cat2, 
                           deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  diabetes_svy_juice2 <- svytable(~diabetes_01 + SSB_master$juice_cat2, design = design)
  diabetes_prop_juice2 <- prop.table(diabetes_svy_juice2, 2)

  
  

# SMOKING
  
  # Soda
  # frequency table
  smoking_table_soda2 <- table(SSB_master$smoking_01, 
                          SSB_master$soda_cat2, 
                          deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  smoking_svy_soda2 <- svytable(~smoking_01 + SSB_master$soda_cat2, design = design)
  smoking_prop_soda2 <- prop.table(smoking_svy_soda2, 2)
  
  # Juice
  # frequency table
  smoking_table_juice2 <- table(SSB_master$smoking_01, 
                          SSB_master$juice_cat2, 
                          deparse.level = 2) # Less than 5% NA
  
  # weighted proportion table
  smoking_svy_juice2 <- svytable(~smoking_01 + SSB_master$juice_cat2, design = design)
  smoking_prop_juice2 <- prop.table(smoking_svy_juice2, 2)
  

# BMI
  
  # Soda
  # frequency table
  bmi_table_soda2 <- table(SSB_master$bmi_cat, 
                      SSB_master$soda_cat2, 
                      deparse.level = 2, useNA = "always") 
                      # <1 category missing more than 5%
  
  # weighted proportion table
  bmi_svy_soda2 <- svytable(~bmi_cat + SSB_master$soda_cat2, design = design)
  bmi_prop_soda2 <- prop.table(bmi_svy_soda2, 2)
  
  # Juice
  # frequency table
  bmi_table_juice2 <- table(SSB_master$bmi_cat, 
                      SSB_master$juice_cat2, 
                      deparse.level = 2, useNA = "always") 
                      # <1 category missing more than 5%
  
  # weighted proportion table
  bmi_svy_juice2 <- svytable(~bmi_cat + SSB_master$juice_cat2, design = design)
  bmi_prop_juice2 <- prop.table(bmi_svy_juice2, 2)
  
  

# ALCOHOL
  
  # frequency table
  # (alcohol_table <- table(SSB_master$alcohol_cat, 
  #                        SSB_master$ssb_cat, 
  #                        deparse.level = 2, useNA = "always"))
  
  # weighted proportion table
  #alcohol_svy <- svytable(~alcohol_cat + ssb_cat, design = design)
  #prop.table(alcohol_svy, 2)

```





```{r table cat2}

tables_cat2 <- rbind(age_prop_soda2, age_prop_juice2, sex_prop_soda2, sex_prop_juice2, education_prop_soda2, education_prop_juice2, exercise_prop_soda2, exercise_prop_juice2, mental_prop_soda2, mental_prop_juice2, diabetes_prop_soda2, diabetes_prop_juice2, smoking_prop_soda2, smoking_prop_juice2, bmi_prop_soda2, bmi_prop_juice2)

#changing into percentage
tables_cat2 <- round(tables_cat2, 2)
tables_cat2 <- tables_cat2*100
tables_cat2[,1:3] <- paste(tables_cat2[,1:3], "%", sep="") 

glimpse(subset(SSB_master, soda_cat2=="0 sodas per Day"))  #26,502  observations
glimpse(subset(SSB_master, soda_cat2=="(0-1) sodas per Day"))  # 22,067 observations
glimpse(subset(SSB_master, soda_cat2=="1+ sodas per Day"))  # 9,022 observations

glimpse(subset(SSB_master, juice_cat2=="0 juices per Day"))  # 32,269 observations
glimpse(subset(SSB_master, juice_cat2=="(0-1) juices per Day"))  # 17,698 observations
glimpse(subset(SSB_master, juice_cat2=="1+ juices per Day"))  # 7,624 observations


# name <- data.frame(Model = c("Age", "18-24", "25-34", "35-44", "45-54", "55-64", "65+", "Sex", "Male", "Female", "Education", "Did not graduate HS", "HS graduate", "Some college", "College graduate", "Exercise", "Exercised in the past 30 days", "No exercise in the past 30 days", "Poor Mental Health Days", "Less than 14", "14 or more", "Diabetes", "No", "Yes", "Current Smoking Status", "Non-smoker", "Smoker", "BMI", "Less than 25", "25-29.9", "30 or higher"))


table1_sodavsother_cat2 <- stargazer(tables_cat2, summary=FALSE, rownames=TRUE, type="html", 
              title = "Table 1. Descriptive statistics of sample by average daily soda vs other SSB.(n = 85,760)",
              align=TRUE,
              style="ajs",
              out="Table1_SodavsOther_cat2.doc")


```



